# Generated by Django 5.0.4 on 2024-04-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_articleimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(blank=True, default='static/article_default.jpg', null=True, upload_to='media/'),
        ),
    ]
