# Generated by Django 5.0.4 on 2024-04-22 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_images', to='api.article'),
        ),
    ]
